# Generated by Django 2.0.4 on 2018-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamindex', '0002_matchteams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red1', models.CharField(max_length=10, unique=True)),
                ('red1_opr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red1_mscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red1_opr_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red1_mscore_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red2', models.CharField(max_length=10, unique=True)),
                ('red2_opr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red2_mscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red2_opr_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('red2_mscore_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue1', models.CharField(max_length=10, unique=True)),
                ('blue1_opr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue1_mscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue1_opr_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue1_mscore_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue2', models.CharField(max_length=10, unique=True)),
                ('blue2_opr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue2_mscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue2_opr_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blue2_mscore_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='MatchTeams',
        ),
    ]
