# Generated by Django 2.0.4 on 2018-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamindex', '0003_auto_20180417_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchteams',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
