# Generated by Django 2.0.4 on 2018-04-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamindex', '0004_researchteams_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='chance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='blue1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matches',
            name='blue2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matches',
            name='red1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matches',
            name='red2',
            field=models.CharField(max_length=10),
        ),
    ]
