# Generated by Django 2.0.4 on 2018-04-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamindex', '0007_auto_20180420_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='blue1_mscore_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='blue1_opr_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='blue2_mscore_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='blue2_opr_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='red1_mscore_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='red1_opr_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='red2_mscore_percentile',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='red2_opr_percentile',
        ),
    ]
