# Generated by Django 2.0.4 on 2018-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamindex', '0008_auto_20180420_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchteams',
            name='l',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchteams',
            name='w',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
